In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import torch.nn as nn

In [11]:
m = torch.rand(1, 1, 8, 8)

In [12]:
m

tensor([[[[0.5013, 0.4131, 0.2342, 0.8533, 0.6713, 0.7971, 0.2847, 0.9583],
          [0.0012, 0.3029, 0.7836, 0.0272, 0.9575, 0.7355, 0.1210, 0.9108],
          [0.0581, 0.0528, 0.6995, 0.9395, 0.9680, 0.8369, 0.2083, 0.3520],
          [0.3052, 0.4492, 0.8673, 0.8860, 0.1031, 0.0997, 0.5165, 0.3787],
          [0.9759, 0.1556, 0.9223, 0.6551, 0.0445, 0.6660, 0.3629, 0.3384],
          [0.8233, 0.7372, 0.8182, 0.2631, 0.2813, 0.4014, 0.7720, 0.9715],
          [0.8406, 0.0444, 0.5660, 0.4520, 0.8756, 0.2503, 0.9741, 0.4815],
          [0.2444, 0.9145, 0.9347, 0.9024, 0.3979, 0.6628, 0.2588, 0.8877]]]])

In [5]:
torch.triu(-1 / torch.tril(m), diagonal=1)

tensor([[[[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
          [0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
          [0., 0., 0., -inf, -inf, -inf, -inf, -inf],
          [0., 0., 0., 0., -inf, -inf, -inf, -inf],
          [0., 0., 0., 0., 0., -inf, -inf, -inf],
          [0., 0., 0., 0., 0., 0., -inf, -inf],
          [0., 0., 0., 0., 0., 0., 0., -inf],
          [0., 0., 0., 0., 0., 0., 0., 0.]]]])

In [6]:
# on CPU
x_cpu = torch.randn(3, 3)
y_cpu = torch.triu(x_cpu)
print(y_cpu.device)

# on GPU (if available)
x_gpu = torch.randn(3, 3, device="cuda")
y_gpu = torch.triu(x_gpu)
print(y_gpu.device)

cpu
cuda:0


## Debug model

In [7]:
from pytorch_builtins_gpt import TransformerBlock

In [8]:
block = TransformerBlock(d_model=8, num_heads=2, dropout=0)

In [20]:
x = torch.rand(2, 5, 8)

In [24]:
block(x)

torch.Size([2, 5, 8])
tensor([[[-0.0789,  0.5913,  0.5830,  0.8026,  0.5740, -0.0664,  0.4228,
           0.3916],
         [ 0.6413,  0.3023,  0.3364,  0.9065,  1.3073,  0.1275,  1.7055,
           1.0846],
         [-0.0806,  0.6261,  0.5745,  0.4485,  1.1097,  0.1737,  1.2850,
           1.1566],
         [ 1.0124,  0.3690,  0.1513,  0.9199,  0.2483,  0.5227,  0.5017,
           1.1933],
         [ 0.7209,  0.3123,  0.3133,  0.5263,  0.8414,  0.6232,  1.1419,
           0.6944]],

        [[ 0.0168,  0.3064,  0.4814,  0.9187,  1.1297, -0.3512,  0.8066,
           0.7304],
         [ 0.6845,  0.8070,  0.5658,  0.3867,  0.9238,  0.5397,  0.5968,
           0.6878],
         [ 1.0328,  0.4977,  0.5323,  0.4931,  1.5019,  0.2396,  0.4266,
           0.3813],
         [ 0.8714,  0.4819,  0.9999,  0.5164,  0.9038,  0.7273,  0.9142,
           0.0634],
         [ 0.2953,  0.6053,  0.4822,  1.2002,  0.5316,  0.0274,  0.4893,
           0.5010]]], grad_fn=<AddBackward0>) torch.Size([2, 5, 8]

tensor([[[-0.7587,  0.6317,  0.4251,  0.5196,  0.2157,  0.4243,  0.5952,
           0.6281],
         [ 0.4705,  0.2822,  0.2313,  0.5632,  0.9445,  0.5070,  1.9887,
           1.3048],
         [-0.3573,  0.6813,  0.3846,  0.1252,  0.8888,  0.4838,  1.5501,
           1.3613],
         [ 1.3194, -0.2095,  0.4341,  0.4298, -0.4383,  1.0834,  0.9573,
           1.4790],
         [ 0.4834,  0.4800,  0.1239,  0.1953,  0.4144,  0.9614,  1.5094,
           0.8563]],

        [[-0.3024,  0.3465,  0.3936,  0.5880,  0.7923,  0.0789,  0.9848,
           0.9335],
         [ 0.1887,  1.0663,  0.4137,  0.0700,  0.3707,  1.0165,  0.8498,
           0.8052],
         [ 0.6755,  0.4095,  0.2903,  0.1865,  0.8950,  0.6904,  0.7940,
           0.6020],
         [ 0.3468,  0.5956,  0.6845,  0.1627,  0.3383,  1.1084,  1.4918,
           0.3676],
         [-0.1851,  0.5284,  0.5235,  0.8646, -0.0323,  0.6530,  0.6308,
           0.7375]]], grad_fn=<AddBackward0>)

In [ ]:
xfm = nn.Transformer(d_model=8, nhead)

In [25]:
v = torch.ones(2, 2)

In [26]:
v

tensor([[1., 1.],
        [1., 1.]])

In [29]:
v[None, ...].shape

torch.Size([1, 2, 2])

In [30]:
x = torch.arange(5)

In [32]:
x

tensor([0, 1, 2, 3, 4])

In [33]:
torch.roll(x, -1)

tensor([1, 2, 3, 4, 0])

In [34]:
torch.argmax(x)

tensor(4)

In [36]:
type(torch.device("cuda"))

torch.device